export const suggestedSearches = [
  "Donald Trump",
  "Joe Biden",
  "The Cultural Revolution",
  "The Three Body Problem",
  "Chile",
  "Canada",
  "Neuroscience",
  "514",
  "818",
  "Google",
  "Software Engineering",
  "Paul Rudd",
  "Jeffrey Epstein",
  "Farming",
  "Regenerative Farming",
  "Minecraft",
  "Quidditch",
  "The Deathly Hallows",
  "Daniel Di Venere",
  "Indie Music",
  "United States",
  "Space Exploration",
  "Climate Change",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Robotics",
  "Quantum Computing",
  "Black Holes",
  "The Solar System",
  "Galaxies",
  "Astronomy",
  "Ancient History",
  "World War II",
  "The Renaissance",
  "Greek Mythology",
  "Ancient Egypt",
  "Mount Everest",
  "The Amazon Rainforest",
  "Great Barrier Reef",
  "Sustainable Energy",
  "Renewable Resources",
  "The Ocean Ecosystem",
  "Wildlife Conservation",
  "Environmental Pollution",
  "Global Warming",
  "Biodiversity",
  "Endangered Species",
  "Virtual Reality",
  "Augmented Reality",
  "Blockchain Technology",
  "Cryptocurrency",
  "SpaceX",
  "Elon Musk",
  "Tesla",
  "Electric Vehicles",
  "Solar Power",
  "Wind Energy",
  "Hydroelectric Power",
  "Nuclear Energy",
  "Biofuels",
  "Organic Farming",
  "Veganism",
  "Covid-19",
  "Pandemics",
  "Vaccination",
  "Telemedicine",
  "Remote Work",
  "Artificial Neural Networks",
  "Quantum Mechanics",
  "Particle Physics",
  "String Theory",
  "The Big Bang Theory",
  "Evolution",
  "Genetics",
  "DNA",
  "Human Genome Project",
  "Astronauts",
  "Cosmic Microwave Background",
  "Hubble Space Telescope",
  "Exoplanets",
  "Colonization of Mars",
  "Aliens and UFOs",
  "Ancient Aliens",
  "Science Fiction",
  "Dystopian Novels",
  "The Matrix",
  "Star Wars",
  "Harry Potter",
  "Lord of the Rings",
  "Marvel Comics",
  "DC Comics",
  "Superheroes",
  "Video Games",
  "Virtual Worlds",
  "Artificial General Intelligence",
  "Deep Learning",
  "Computer Vision",
  "Natural Language Processing",
  "Machine Translation",
  "Robotics",
  "Automation",
  "Space Travel",
  "Extraterrestrial Life",
  "Astrobiology",
  "Quantum Entanglement",
  "Time Travel",
  "Parallel Universes",
  "Climate Action",
  "Renewable Energy Sources",
  "Clean Water Access",
  "Human Rights",
  "Social Justice",
  "Gender Equality",
  "Mental Health Awareness",
  "Mindfulness Meditation",
  "Yoga and Wellness",
  "Healthy Eating",
  "Cooking and Recipes",
  "Gardening",
  "Home Improvement",
  "DIY Crafts",
  "Travel Destinations",
  "Hiking and Camping",
  "Photography",
  "Art and Creativity",
  "Music Production",
  "Film and Cinema",
  "Books and Literature",
  "Philosophy",
  "Ethics",
  "Political Science",
  "Economics",
  "Sociology",
  "Psychology",
  "History of Art",
  "Classical Music",
  "Rock and Roll",
  "Hip Hop Culture",
  "Electronic Dance Music",
  "Futurism",
  "Cybersecurity",
  "Privacy Online",
  "Cryptocurrencies",
  "E-commerce Trends",
  "Remote Education",
  "Gaming Industry",
  "Esports",
  "Board Games",
  "Space Telescopes",
  "Quantum Computers",
  "The Universe's Fate",
  "Mars Colonization",
  "Astronomy Photography",
  "Ancient Civilizations",
  "Archaeology Discoveries",
  "Sustainable Fashion",
  "Interior Design",
  "Home Decor Trends",
  "Personal Finance",
  "Investment Strategies",
  "Cryptocurrency Investments",
  "Travel Tips",
  "Adventure Travel",
  "National Parks",
  "Wildlife Photography",
  "Environmental Conservation",
  "Climate Change Mitigation",
  "Renewable Energy Innovation",
  "Space Tourism",
  "Astrophotography",
  "Exoplanet Exploration",
  "Deep Space Missions",
  "Alternative Energy Sources",
  "Beekeeping",
  "Aquaponics",
  "Urban Gardening",
  "DIY Home Repairs",
  "Baking and Pastry",
  "World Cuisine",
  "Mediterranean Diet",
  "Plant-Based Diet",
  "Fitness and Exercise",
  "Outdoor Workouts",
  "Mental Health Support",
  "Self-Care Practices",
  "Online Learning",
  "Web Development",
  "Mobile App Development",
  "Game Development",
  "Graphic Design",
  "Content Creation",
  "Social Media Marketing",
  "Digital Nomad Lifestyle",
  "Remote Job Opportunities",
  "Online Business Ideas",
  "Eco-Friendly Living",
  "Green Energy Solutions",
  "Social Entrepreneurship",
  "Leadership Skills",
  "Effective Communication",
  "Conflict Resolution",
  "Positive Psychology",
  "Mindful Parenting",
  "Pet Care and Training",
  "Animal Adoption",
  "Outdoor Adventures",
  "Extreme Sports",
  "DIY Electronics",
  "Home Automation",
  "3D Printing",
  "Virtual Reality Gaming",
  "Augmented Reality Apps",
  "Futuristic Technology",
  "Artificial Intelligence Ethics",
  "Data Privacy Protection",
  "Cybersecurity Threats",
  "Space Colonization Challenges",
  "Alien Contact Theories",
  "Consciousness Studies",
  "Philosophy of Science",
  "Environmental Ethics",
  "Sustainable Architecture",
  "Historical Mysteries",
  "Unsolved Crimes",
  "Literary Classics",
  "Contemporary Literature",
  "Cinema Masterpieces",
  "Art Movements",
  "Music Genres",
  "Cultural Diversity",
];


export const searchableSuggestions = [
  "cryptocurrency investments",
  "remote job opportunities",
  "farming",
  "effective communication",
  "star wars",
  "climate change mitigation",
  "donald trump",
  "exoplanet exploration",
  "vaccination",
  "great barrier reef",
  "solar power",
  "augmented reality",
  "human rights",
  "farming",
  "art movements",
  "global warming",
  "personal finance",
  "astronauts",
  "healthy eating",
  "effective communication",
  "paul rudd",
  "sustainable fashion",
  "home improvement",
  "jeffrey epstein",
  "neuroscience",
  "cinema masterpieces",
  "psychology",
  "alien contact theories",
  "ancient history",
  "rock and roll",
  "virtual worlds",
  "philosophy",
  "cooking and recipes",
  "electric vehicles",
  "self-care practices",
  "data science",
  "augmented reality apps",
  "books and literature",
  "sustainable energy",
  "national parks",
  "exoplanet exploration",
  "environmental pollution",
  "mediterranean diet",
  "cybersecurity threats",
  "telemedicine",
  "quantum computing",
  "remote education",
  "galaxies",
  "cosmic microwave background",
  "art movements",
  "elon musk",
  "ancient aliens",
  "healthy eating",
  "virtual reality",
  "pet care and training",
  "robotics",
  "home automation",
  "alien contact theories",
  "canada",
  "interior design",
  "514",
  "remote education",
  "eco-friendly living",
  "content creation",
  "minecraft",
  "ancient history",
  "content creation",
  "music production",
  "computer vision",
  "colonization of mars",
  "artificial intelligence",
  "robotics",
  "cryptocurrency investments",
  "conflict resolution",
  "string theory",
  "personal finance",
  "astronauts",
  "artificial neural networks",
  "aliens and ufos",
  "futuristic technology",
  "extraterrestrial life",
  "514",
  "aliens and ufos",
  "colonization of mars",
  "spacex",
  "818",
  "adventure travel",
  "social entrepreneurship",
  "social media marketing",
  "political science",
  "artificial intelligence",
  "cryptocurrency",
  "wildlife conservation",
  "interior design",
  "biofuels",
  "lord of the rings",
  "game development",
  "hip hop culture",
  "history of art",
  "gaming industry",
  "archaeology discoveries",
  "514",
  "artificial intelligence ethics",
  "gardening",
  "effective communication",
  "indie music",
  "artificial intelligence",
  "star wars",
  "archaeology discoveries",
  "philosophy",
  "dystopian novels",
  "ancient history",
  "adventure travel",
  "the deathly hallows",
  "positive psychology",
  "economics",
  "donald trump",
  "art movements",
  "yoga and wellness",
  "pandemics",
  "ancient egypt",
  "the three body problem",
  "data science",
  "renewable energy innovation",
  "augmented reality",
  "national parks",
  "3d printing",
  "virtual worlds",
  "artificial intelligence ethics",
  "renewable energy sources",
  "black holes",
  "board games",
  "space colonization challenges",
  "great barrier reef",
  "quantum computers",
  "quantum mechanics",
  "esports",
  "exoplanet exploration",
  "greek mythology",
  "robotics",
  "daniel di venere",
  "quantum computing",
  "cryptocurrencies",
  "plant-based diet",
  "effective communication",
  "ancient history",
  "parallel universes",
  "biodiversity",
  "machine learning",
  "dystopian novels",
  "indie music",
  "cryptocurrency",
  "home decor trends",
  "the solar system",
  "augmented reality",
  "mindfulness meditation",
  "human genome project",
  "robotics",
  "astronauts",
  "gaming industry",
  "quidditch",
  "board games",
  "gaming industry",
  "evolution",
  "investment strategies",
  "the solar system",
  "positive psychology",
  "dna",
  "mindful parenting",
  "hip hop culture",
  "aquaponics",
  "cosmic microwave background",
  "self-care practices",
  "mediterranean diet",
  "mount everest",
  "climate change mitigation",
  "lord of the rings",
  "quidditch",
  "augmented reality",
  "space travel",
  "contemporary literature",
  "interior design",
  "exoplanets",
  "mindful parenting",
  "hubble space telescope",
  "wildlife photography",
  "space exploration",
  "exoplanet exploration",
  "covid-19",
  "dc comics",
  "robotics",
  "mental health support",
  "mental health awareness",
  "national parks",
  "solar power",
  "travel tips",
  "machine learning",
  "quantum entanglement",
  "diy electronics",
  "quidditch",
  "clean water access",
  "adventure travel",
  "national parks",
  "computer vision",
  "conflict resolution",
  "environmental pollution",
  "positive psychology",
  "galaxies",
  "genetics",
  "quantum computing",
  "spacex",
  "space telescopes",
  "beekeeping",
  "machine translation",
  "mental health awareness",
  "baking and pastry",
  "genetics",
  "electric vehicles",
  "particle physics",
  "the deathly hallows",
  "human rights",
  "psychology",
  "climate action",
  "world war ii",
  "3d printing",
  "software engineering",
  "514",
  "ancient civilizations",
  "online learning",
  "diy home repairs",
  "artificial intelligence ethics",
  "home improvement",
  "mount everest",
  "covid-19",
  "colonization of mars",
  "electric vehicles",
  "mental health support",
  "space colonization challenges",
  "gardening",
  "literary classics",
  "quantum mechanics",
  "galaxies",
  "united states",
  "chile",
  "human rights",
  "remote education",
  "game development",
  "baking and pastry",
  "yoga and wellness",
  "great barrier reef",
  "mount everest",
  "board games",
  "conflict resolution",
  "deep space missions",
  "robotics",
  "contemporary literature",
  "genetics",
  "renewable energy innovation",
  "mobile app development",
  "human rights",
  "machine translation",
  "renewable resources",
  "animal adoption",
  "space travel",
  "art and creativity",
  "futuristic technology",
  "evolution",
  "cryptocurrency",
  "virtual reality",
  "artificial general intelligence",
  "818",
  "deep space missions",
  "quantum entanglement",
  "virtual worlds",
  "remote work",
  "marvel comics",
  "robotics",
  "art movements",
  "deep learning",
  "exoplanets",
  "climate change",
  "historical mysteries",
  "artificial general intelligence",
  "ethics",
  "renewable energy sources",
  "extreme sports",
  "futuristic technology",
  "sustainable energy",
  "spacex",
  "interior design",
  "diy electronics",
  "esports",
  "exoplanets",
  "dystopian novels",
  "pet care and training",
  "renewable energy innovation",
  "nuclear energy",
  "quantum mechanics",
  "diy home repairs",
  "art and creativity",
  "organic farming",
  "sociology",
  "travel destinations",
  "extraterrestrial life",
  "effective communication",
  "cryptocurrency investments",
  "history of art",
  "harry potter",
  "artificial neural networks",
  "social justice"
]